#set(AARCH64_TOOLCHAIN_BIN /source/bm1880/host-tools/gcc/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/)
if (NOT DEFINED AARCH64_TOOLCHAIN_BIN)
    set (AARCH64_TOOLCHAIN_BIN "")
endif()
set(ARCH aarch64-linux-gnu-)
set(CMAKE_C_COMPILER ${AARCH64_TOOLCHAIN_BIN}${ARCH}gcc)
set(CMAKE_CXX_COMPILER ${AARCH64_TOOLCHAIN_BIN}${ARCH}g++)