// Stream
#define STREAM_CMD "command"
#define STREAM_CMD_RESP "command_resp"
#define STREAM_REGISTER_FACE "register_face"

// Context
#define CONTEXT_KEY_SERVER_VERSION "server_version"
#define CONTEXT_KEY_USE_DEMUX "use_demux"
#define CONTEXT_KEY_STREAM_CMD "stream_command"
#define CONTEXT_KEY_STREAMS "streams"

// Config
#define CONFIG_KEY_SERVER_VERSION "server_version"
#define CONFIG_KEY_STM_DISABLE "stream_disable"
#define CONFIG_KEY_STM_SRC_TYPE "source_type"
#define CONFIG_KEY_STM_SRC_DEVICE "device"
#define CONFIG_KEY_STM_SRC_DEVICE_IDX "source_device_index"
#define CONFIG_KEY_STM_SRC_RTSP "rtsp"
#define CONFIG_KEY_STM_SRC_RTSP_HOST "source_rtsp_host"
#define CONFIG_KEY_STM_SRC_RTSP_PORT "source_rtsp_port"
#define CONFIG_KEY_STM_SRC_RTSP_URL "source_rtsp_url"
#define CONFIG_KEY_STM_DEST_TYPE "destination_type"
#define CONFIG_KEY_STM_DEST_TTY "tty"
#define CONFIG_KEY_STM_DEST_HTTP "http"
#define CONFIG_KEY_STM_DEST_HTTP_WITH_FACES "http_with_faces"
#define CONFIG_KEY_STM_DEST_HTTP_HOST "destination_http_host"
#define CONFIG_KEY_STM_DEST_HTTP_PORT "destination_http_port"
#define CONFIG_KEY_STM_DEST_HTTP_URL "destination_http_url"
#define CONFIG_KEY_STM_DEST_HTTP_FACES_URL "destination_http_faces_url"
#define CONFIG_KEY_REPO "repository"
#define CONFIG_KEY_DETECTOR "detector"
#define CONFIG_KEY_DETECTOR_MODEL "detector_models"
#define CONFIG_KEY_EXTRACTOR "extractor"
#define CONFIG_KEY_EXTRACTOR_MODEL "extractor_models"
#define CONFIG_KEY_STM_PREFIX "stream_"
#define CONFIG_KEY_CMD_STM_DISABLE "command_disable"
#define CONFIG_KEY_STM_AUTO_START "auto_start"
#define CONFIG_KEY_STM_FACE_ANTI_SPOOFING "face_anti_spoofing"
#define CONFIG_KEY_STM_FACE_ANTI_SPOOFING_MODELS "face_anti_spoofing_models"
#define CONFIG_KEY_STM_FACE_ANTI_SPOOFING_LABEL "face_anti_spoofing_label"

// Command
#define CMD_REGISTER_FACE "register_face"
#define CMD_GET_CMDS "get_commands"
#define CMD_GET_SERVER_VERSION "get_server_version"
#define CMD_STOP_SERVER "stop_server"
#define CMD_GET_STREAMS "get_streams"
#define CMD_START_STREAMS "start_stream"
#define CMD_PAUSE_STREAMS "pause_stream"
#define CMD_STOP_STREAMS "stop_stream"

#define CMD_RESP_UNKNOWN "Unknown command"
